### ISSUE TITLE
How do dns4s respond on incorrect client request ?

### ISSUE THREAD

**Issue by Mefl** [mkroli/dns4s#13]
Hi,

As you know dns is a standard but some client miss implement it, so I wonder know if you practiced some tests with bad clients to know how it respond ?
Do you use it in production ? and did experiments some specials defects ?

I would like to use dns4s to implement a custom dns server on medium traffic, so I will really appreciate your answer and let me know if i can do something to help ;)

Emmanuel

**Comment by mkroli** [comment]
I tested primarily with dig. Can you elaborate which bad clients you mean? I don't use it in production. It has no defects that I'm aware of but the code is unit tested.

I would really like to see it being used in production. So far nothing comes to my mind where I could need your help but for example not all record types are implemented so if you require a type which is not implemented your contribution would obviously be welcome.
