### ISSUE TITLE
How do you return a list of answers?

### ISSUE THREAD

**Issue by i-am-the-slime** [mkroli/dns4s#2]
This doesn't work:

```[scala]
addresses = List("1.2.3.4", "2.3.4.5") //This is constructed, I do a lookup in order to get the list
val records: List[ResourceRecordModifier] = addresses.map(str ⇒ {
  ARecord(str)
})
Response ~ Questions(host) ~ Answers(records: _*)
```

It is not allowed to put the _* in there.

**Comment by mkroli** [comment]
```Answers.apply``` expects ```ResourceRecord*``` however you pass ```ResourceRecordModifier*```.
There is an implicit conversion from ```ResourceRecordModifier``` to ```ResourceRecord``` which unfortunately is not used automatically due to the use of ```ResourceRecordModifier``` inside a ```List```.

Probably there should be a version of ```Answers.apply``` which expects ```ResourceRecordModifier*```.

However as a quick solution you could simply trigger the conversion manually inside ```map```:
```scala
val addresses = List("1.2.3.4", "2.3.4.5") //This is constructed, I do a lookup in order to get the list
val records: List[ResourceRecord] = addresses.map(str ⇒ {
  ARecord(str): ResourceRecord
})
Response ~ Questions(host) ~ Answers(records: _*)
```

**Comment by i-am-the-slime** [comment]
Cool, that works, thanks!
