### ISSUE TITLE
No version released for scala 2.11.

### ISSUE THREAD

**Issue by faizanahemad** [mkroli/dns4s#5]
Hi,
The current version 0.9 can only be used with akka-actor_2.10, attempts to use with akka-actor_2.11 throws error. [This SO question](http://stackoverflow.com/questions/25743684/how-can-spray-io-work-with-scala-2-11-1-akka-2-3-2) shows a similar scenario with spray. The error is same in this case too.
Can we release a version for scala 2.11? I would be glad to make a PR but I am not sure what changes would be needed. Any guidance will be great.
I will try to compile this with 2.11 on local and post the results here.

**Comment by mkroli** [comment]
There already should be a version for Scala 2.11. Have you had a look at [examples/simple/build.sbt](https://github.com/mkroli/dns4s/blob/master/examples/simple/build.sbt)? It is an example DNS-Server using Scala 2.11 and akka-actor_2.11.

Can you maybe provide your sbt build file so I can reproduce it?

**Comment by faizanahemad-flipster** [comment]
Hi yes took a look. That is great man! I had not searched in jcenter repo. Should have done that.
I included _dns4s-core_ as well. Does the dns4s-akka itself has the core package (as dependency) ?.

Aside question:- are reverse dns lookup queries supported as well?
Great project btw, I learnt some new scala features here (I am scala noob).

**Comment by faizanahemad** [comment]
Hi yes took a look. That is great man! I had not searched in jcenter repo. Should have done that.
I included _dns4s-core_ as well. Does the dns4s-akka itself has the core package (as dependency) ?.

Aside question:- are reverse dns lookup queries supported as well?
Great project btw, I learnt some new scala features here (I am scala noob).

**Comment by mkroli** [comment]
```dns4s-akka``` depends on ```dns4s-core``` so you don't need to explicitly include ```dns4s-core``` as a dependency.

Reverse lookups would work like the following:
```scala
IO(Dns) ? Dns.DnsPacket(Query ~ Questions(QName("8.8.8.8.in-addr.arpa") ~ TypePTR), new InetSocketAddress("8.8.8.8", 53)) onSuccess {
  case Response(Answers(answers)) =>
    answers.collect {
      case PTRRecord(ptrdname) => println(ptrdname)
    }
}
```
