### ISSUE TITLE
eDNS client ip option 

### ISSUE THREAD

**Issue by whatvn** [mkroli/dns4s#7]
Hello, 

I am looking for [EDNS0](https://tools.ietf.org/html/draft-vandergaast-edns-client-ip-00) implementation in order to get client address of dns queries. 

Reading current dns4s source code, I am unable to find that implementation or did i miss something? 

Could you please provide some guide lines? 

Thanks

**Comment by mkroli** [comment]
see #8

**Comment by mkroli** [comment]
Implemented, please see [ClientSubnetOption in DSL Documentation](https://github.com/mkroli/dns4s/blob/master/dsl.md#clientsubnetoption).
